# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['/Users/usuario/Documents/Proyecto_punto_venta/VentasUniforme/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('ventas/ventas.kv', 'ventas'),
        ('ventas/logo_columbia.png', 'ventas'),
        ('signin/signin.kv', 'signin'),
        ('signin/logo_columbia.png', 'signin'),
        ('admin/admin.kv', 'admin'),
        ('admin/logo_columbia.png', 'admin'),
        ('fonts/playwrite-ca-light.ttf','fonts'),
        ('fonts/birthstone-bounce-medium.ttf','fonts'),
        ('databases/uniformes.sqlite', 'databases'),
        ('assets/logo_columbia.png','assets'),
        ('assets/logo_columbia_inventario.png','assets'),
        ('assets/logo_columbia_ticket.png','assets'),
        ('inventario','inventario'),
        ('tickets','tickets'),
        ('resources/version.txt', 'resources'),
        ('icons/CS.icns', 'icons')
    ],
    hiddenimports=[
        'kivy',
        'kivy.clock',
        'kivy._clock',
        'kivy.core.window',
        'kivy.core.window.window_sdl2',
        'kivy.core.text',
        'kivy.core.image',
        'kivy.core.clipboard',
        'kivy.uix.image',
        'kivy.core.text.markup',
        'kivy.core.text.text_layout',
        'kivy.support',
        'kivy.deps.sdl2',
        'kivy.deps.glew',
        'kivy.graphics',
        'kivy.graphics.context_instructions',
        'kivy.graphics.compiler',
        'kivy.graphics.shader',
        'kivy.graphics.texture',
        'kivy.graphics.transformation',
        'kivy.graphics.vertex_instructions',
        'os',
        'sys',
        'kivy.uix.popup',
        'kivy.uix.label',
        'kivy.uix.button',
        'kivy.uix.boxlayout',
        'kivy.app',
        'kivy.uix.screenmanager',
        'kivy.resources',
        'kivy.lang',
        'kivy.uix.recycleview',
        'kivy.uix.recycleview.views',
        'kivy.properties',
        'kivy.uix.recycleboxlayout',
        'kivy.uix.behaviors',
        'kivy.uix.recycleview.layout',
        'kivy.uix.dropdown',
        'kivy.uix.filechooser',
        'datetime',
        'csv',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.lib.styles',
        'reportlab.platypus',
        'reportlab.lib.enums',
        'reportlab.pdfbase',
        'reportlab.pdfbase.ttfonts',
        'smtplib',
        'email.mime.multipart',
        'email.mime.base',
        'email.mime.text',
        'email',
        'reportlab.pdfgen',
        'pathlib',
        'sqlite3',
        'logging',
        'logging.handlers'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['_tkinter', 'Tkinter', 'enchant', 'twisted'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='touchtracer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icons/CS.icns'
)
coll = COLLECT(
    exe,
    Tree('/Users/usuario/Documents/Proyecto_punto_venta/VentasUniforme'),
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='touchtracer'
)
app = BUNDLE(
    coll,
    name='touchtracer.app',
    icon=None,
    bundle_identifier=None,
)
